### ISSUE TITLE
NullPointerException when database user has no password

### ISSUE THREAD

**Issue by mscarlett** [r78v10a07/jbiowh-persistence#1]
I encounter a NullPointerException when running the jbiowh-parser tool from the command line with the following configuration file:

```
<warehouse>
    <name>DrugBank</name>
    <type>DrugBank</type>
    <version>3.0</version>
    <homeurl>http://drugbank.ca</homeurl>
    <releaseDate>09/09/2011</releaseDate>
    <database>jbiowh</database>
    <dbuser>root</dbuser>
    <dbpassword></dbpassword>
    <directory>./drugbank</directory>
    <temporal>./temp</temporal>
    <driver>com.mysql.jdbc.Driver</driver>
    <url>jdbc:mysql://localhost:3306/</url>
    <xsdfiledef></xsdfiledef>
    <verbose>info</verbose>
    <droptables>true</droptables>
    <runlinks>true</runlinks>
</warehouse>
```

and this is the error message I receive:

```
INFO [main] 2015-07-15 16:57:37,743 -        MySQL: Open the MySQL connection
  Exception in thread "main" java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at org.jbiowhdbms.dbms.mysql.WHMySQL.openConnection(WHMySQL.java:82)
        at org.jbiowhdbms.dbms.mysql.WHMySQL.createStatement(WHMySQL.java:706)
        at org.jbiowhdbms.dbms.mysql.WHMySQL.executeUpdate(WHMySQL.java:351)
        at org.jbiowhparser.datasets.drug.drugbank.DrugBankParser.runLoader(DrugBankParser.java:60)
        at org.jbiowhparser.DataSetLoader.dataSetLoader(DataSetLoader.java:154)
        at org.jbiowhparser.DataSetLoader.main(DataSetLoader.java:174)
```

I believe that the error is due to not using a password. The parser program runs successfully after editing the configuration file to include a user with a password.

**Comment by r78v10a07** [comment]
Hi mscarlett,
Thank you for point it out. I have fixed it, so you can use JBioWH without mysql password from now on.
Regards,
Roberto
